select
  ts.season
, ts.week
, ts.team
, ts.season_type
, ts.game_id
, ts.opponent_team
, ts.completions
, ts.attempts
, ts.passing_yards
, ts.passing_tds
, ts.passing_interceptions
, ts.sacks_suffered
, ts.sack_yards_lost
, ts.sack_fumbles
, ts.sack_fumbles_lost
, ts.passing_air_yards
, ts.passing_yards_after_catch
, ts.passing_first_downs
, ts.passing_epa
, ts.passing_cpoe
, ts.passing_2pt_conversions
, ts.passing_10
, ts.passing_16
, ts.passing_20
, ts.passing_40
, ts.carries
, ts.rushing_yards
, ts.rushing_tds
, ts.rushing_fumbles
, ts.rushing_fumbles_lost
, ts.rushing_first_downs
, ts.rushing_epa
, ts.rushing_2pt_conversions
, ts.rushing_10
, ts.rushing_12
, ts.rushing_20
, ts.rushing_40
, ts.receptions
, ts.targets
, ts.receiving_yards
, ts.receiving_tds
, ts.receiving_fumbles
, ts.receiving_fumbles_lost
, ts.receiving_air_yards
, ts.receiving_yards_after_catch
, ts.receiving_first_downs
, ts.receiving_epa
, ts.receiving_2pt_conversions
, ts.receiving_10
, ts.receiving_16
, ts.receiving_20
, ts.receiving_40
, ts.special_teams_tds
, ts.def_tackles_solo
, ts.def_tackles_with_assist
, ts.def_tackle_assists
, ts.def_tackles_for_loss
, ts.def_tackles_for_loss_yards
, ts.def_fumbles_forced
, ts.def_sacks
, ts.def_sack_yards
, ts.def_qb_hits
, ts.def_interceptions
, ts.def_interception_yards
, ts.def_pass_defended
, ts.def_tds
, ts.def_fumbles
, ts.def_safeties
, ts.def_punt_blocks
, ts.def_pat_blocks
, ts.def_fg_blocks
, ts.def_2pt_atts
, ts.def_2pt_made
, ts.misc_yards
, ts.fumble_recovery_own
, ts.fumble_recovery_yards_own
, ts.fumble_recovery_opp
, ts.fumble_recovery_yards_opp
, ts.fumble_recovery_tds
, ts.penalties
, ts.penalty_yards
, ts.timeouts
, ts.fumbles_forced_by_opp
, ts.fumbles_not_forced
, ts.fumbles_out_of_bounds
, ts.fumbles_total
, ts.fumbles_lost_total
, ts.punt_returns
, ts.punt_return_yards
, ts.kickoff_returns
, ts.kickoff_return_yards
, ts.fg_made
, ts.fg_att
, ts.fg_missed
, ts.fg_blocked
, ts.fg_long
, ts.fg_pct
, ts.fg_made_0_19
, ts.fg_made_20_29
, ts.fg_made_30_39
, ts.fg_made_40_49
, ts.fg_made_50_59
, ts.fg_made_60_
, ts.fg_missed_0_19
, ts.fg_missed_20_29
, ts.fg_missed_30_39
, ts.fg_missed_40_49
, ts.fg_missed_50_59
, ts.fg_missed_60_
, ts.fg_made_list
, ts.fg_missed_list
, ts.fg_blocked_list
, ts.fg_made_distance
, ts.fg_missed_distance
, ts.fg_blocked_distance
, ts.pat_made
, ts.pat_att
, ts.pat_missed
, ts.pat_blocked
, ts.pat_pct
, ts.gwfg_made
, ts.gwfg_att
, ts.gwfg_missed
, ts.gwfg_blocked
, ts.gwfg_distance
, ts.pt_att
, ts.pt_blocked
, ts.pt_long
, ts.pt_yards
, ts.pt_inside_20
, ts.pt_out_of_bounds
, ts.pt_downed
, ts.pt_touchback
, ts.pt_fair_caught
, ts.pt_returned
, ts.pt_return_yards
, ts.pt_return_tds
, ts.pt_net_yards
FROM read_parquet('${bucket}/bronze/team_stats/season=*/team_stats.parquet', union_by_name = true) ts