select
  ws.season
, ws.player_id as gsis_id
, ws.player_name
, ws.player_display_name
, ws.position
, ws.position_group
, ws.headshot_url
, ws.week
, ws.season_type
, ws.game_id
, cm_t.target
, ws.opponent_team
, ws.completions
, ws.attempts
, ws.passing_yards
, ws.passing_tds
, ws.passing_interceptions
, ws.sacks_suffered
, ws.sack_yards_lost
, ws.sack_fumbles
, ws.sack_fumbles_lost
, ws.passing_air_yards
, ws.passing_yards_after_catch
, ws.passing_first_downs
, ws.passing_epa
, ws.passing_cpoe
, ws.passing_2pt_conversions
, ws.pacr
, ws.passing_10
, ws.passing_16
, ws.passing_20
, ws.passing_40
, ws.carries
, ws.rushing_yards
, ws.rushing_tds
, ws.rushing_fumbles
, ws.rushing_fumbles_lost
, ws.rushing_first_downs
, ws.rushing_epa
, ws.rushing_2pt_conversions
, ws.rushing_10
, ws.rushing_12
, ws.rushing_20
, ws.rushing_40
, ws.receptions
, ws.targets
, ws.receiving_yards
, ws.receiving_tds
, ws.receiving_fumbles
, ws.receiving_fumbles_lost
, ws.receiving_air_yards
, ws.receiving_yards_after_catch
, ws.receiving_first_downs
, ws.receiving_epa
, ws.receiving_2pt_conversions
, ws.receiving_10
, ws.receiving_16
, ws.receiving_20
, ws.receiving_40
, ws.racr
, ws.target_share
, ws.air_yards_share
, ws.wopr
, ws.special_teams_tds
, ws.def_tackles_solo
, ws.def_tackles_with_assist
, ws.def_tackle_assists
, ws.def_tackles_for_loss
, ws.def_tackles_for_loss_yards
, ws.def_fumbles_forced
, ws.def_sacks
, ws.def_sack_yards
, ws.def_qb_hits
, ws.def_interceptions
, ws.def_interception_yards
, ws.def_pass_defended
, ws.def_tds
, ws.def_fumbles
, ws.def_safeties
, ws.def_punt_blocks
, ws.def_pat_blocks
, ws.def_fg_blocks
, ws.def_2pt_atts
, ws.def_2pt_made
, ws.misc_yards
, ws.fumble_recovery_own
, ws.fumble_recovery_yards_own
, ws.fumble_recovery_opp
, ws.fumble_recovery_yards_opp
, ws.fumble_recovery_tds
, ws.penalties
, ws.penalty_yards
, ws.fumbles_forced_by_opp
, ws.fumbles_not_forced
, ws.fumbles_out_of_bounds
, ws.fumbles_total
, ws.fumbles_lost_total
, ws.punt_returns
, ws.punt_return_yards
, ws.kickoff_returns
, ws.kickoff_return_yards
, ws.fg_made
, ws.fg_att
, ws.fg_missed
, ws.fg_blocked
, ws.fg_long
, ws.fg_pct
, ws.fg_made_0_19
, ws.fg_made_20_29
, ws.fg_made_30_39
, ws.fg_made_40_49
, ws.fg_made_50_59
, ws.fg_made_60_
, ws.fg_missed_0_19
, ws.fg_missed_20_29
, ws.fg_missed_30_39
, ws.fg_missed_40_49
, ws.fg_missed_50_59
, ws.fg_missed_60_
, ws.fg_made_list
, ws.fg_missed_list
, ws.fg_blocked_list
, ws.fg_made_distance
, ws.fg_missed_distance
, ws.fg_blocked_distance
, ws.pat_made
, ws.pat_att
, ws.pat_missed
, ws.pat_blocked
, ws.pat_pct
, ws.gwfg_made
, ws.gwfg_att
, ws.gwfg_missed
, ws.gwfg_blocked
, ws.gwfg_distance
, ws.pt_att
, ws.pt_blocked
, ws.pt_long
, ws.pt_yards
, ws.pt_inside_20
, ws.pt_out_of_bounds
, ws.pt_downed
, ws.pt_touchback
, ws.pt_fair_caught
, ws.pt_returned
, ws.pt_return_yards
, ws.pt_return_tds
, ws.pt_net_yards
, ws.fantasy_points
, ws.fantasy_points_ppr
from read_parquet('s3://fantasy-football-dev-808943963151-ca-central-1-an/bronze/weekly_stats/season=*/weekly_stats.parquet', union_by_name = true) ws
left outer join read_csv('s3://fantasy-football-dev-808943963151-ca-central-1-an/mappings/club_mapping.csv') cm_t
  on ws.team = cm_t.source